### ISSUE TITLE
Cannot get dashboard working

### ISSUE THREAD

**Issue by bushvin** [DreamOfIce/grafana-podman-dashboard#1]
Hello,

I am trying to get your (english) dashboard to run on my prometheus/grafana setup, but no luck.
Could you elaborate on how to set it up properly?

Grafana v10.4.3
Prometheus v2.52.0
prometheus-podman-exporter v1.11.1

prometheus.yml:
```yml
  - job_name: "podman"
    static_configs:
      - targets:
        - "localhost:9882"
```

![Screenshot_20240530_100430](https://github.com/DreamOfIce/grafana-podman-dashboard/assets/4785760/abb9185c-cea9-4211-bcc2-ae96ddec8e68)
